### PR TITLE
Added support for custom ports.

### LINKED ISSUE #149: Can't run gui on custom port.
### Description
If running the gui on a custom port by using the cli the gui fails to login and returns `unable to connect`.

A closer look at the browser console shows the following:

Some inverstigations showed that this is caused by a hardcoded value in the gui:

```ts
      useValue: `http://${window.location.hostname}:2400`
```
### How to reproduce
Launch Chatoverflow on a custom port:
```
java -jar ChatOverflow.jar -w 7020
```

### References
GUI file with hardcoded value: 
https://github.com/codeoverflow-org/chatoverflow-gui/blob/07ae4c9b2ebf961a8531b36eb69ae7891ce3ce76/src/app/app.module.ts#L27

Discussion on discord: 
https://discordapp.com/channels/577412066994946060/577412067435216896/640614386590941244

### PR DESCRIPTION
**Pull request by derNiklaas**
This is not tested (cause sbt gui doesn't work for me)

see: https://developer.mozilla.org/en-US/docs/Web/API/Location
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/host

Fixes https://github.com/codeoverflow-org/chatoverflow/issues/149

### CODE REVIEW

**Comment by hlxid** [comment]
This is fine when the GUI is served by the framework, but running `ng serve` should still be supported for web devs that want to quickly see their changes and don't want to restart the framework. 
In case of `ng serve` it will be hosted at `:4200` and Rest API request will fail, because it isn't the framework.

Angular has built in support to proxy those http requests to another port, in our case the framework at `:2400`: https://angular.io/guide/build#proxying-to-a-backend-server It would be very nice if you could implement it @derNiklaas. The port is usually changed in actual deployments and developers should mostly use the default port, so I think that hardcoding `:2400` for `ng serve` is fine.

**Comment by derNiklaas** [comment]
You can add —port <Port> to  ng serve which will run the application on a different Port.
Also you can add an Option to the angular config which will Change the default port.

**Comment by hlxid** [comment]
Sure, you can change the port, but it doesn’t solve the problem.

Your current code will use the port of the server, which serves the GUI, also as the port for the ChatOverflow REST Api. This works when the GUI is served by the ChatOverflow framework. E.g. you change the port with the cli flag to be 7000 instead of the default 2400. Then the GUI is served by `localhost:7000` and your code then also performs all Api calls on the same host(`localhost:7000`), which works, because thats the port of the framework and therefore fixes the issue you referenced.

The problem when using `ng serve`, which is a use case we want to support, is that the browser gets the GUI from `localhost:4200` (or any other port as changed by the config/flag you mentioned) and your code therefore also uses `localhost:4200` as the host for the ChatOverflow Rest API, which is used to start plugins and so on. The problem is that `localhost:4200` is the server of `ng serve` and responds with 404s, because it doesn’t know what to do with the ChatOverflow Api requests. Instead these requests should be going to `localhost:2400`, the default port of the framework, which can process the requests and e.g. start plugins. As stated in my previous message I think we can assume that developers using `ng serve` will use the default port(`:2400`).

Instead of trying to detect if the gui is served using `ng serve`, which would be rather hard, you can follow the above linked docs to tell angular that it should forward all requests, which it can’t handle, to the framework at `:2400` and thus can fix the above described problem, which will allow the use of `ng serve` because the api requests actually get to the framework.

**Comment by hlxid** [comment]
@derNiklaas I have some time available today so I could also implement my suggestion if you don't mind or already started working on it.

**Pull request merged**
